debug: true
server:
  port: 8082
dubbo:
  application:
    name: demo-service-web
  registry:
    register: false
    id: zk_2181
    address: zookeeper://127.0.0.1:2181
    group: demo
  consumer:
    check: false
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

#  rabbitmq:
#    host: 0.0.0.0
#    port: 5672
#    virtual-host: test
#    username: admin
#    password: admin
#    listener:
#      simple:
#        retry:
#          enabled: true
#          max-attempts: 1
#          initial-interval: 30000ms
#        default-requeue-rejected: false
#        prefetch: 1
